[build-system]
requires = ["maturin>=1.0,<2.0"]

build-backend = "maturin"

[tool.maturin]
bindings = "pyo3"

[project]
name = "rraft-py"
requires-python = ">=3.10"
description = "Unofficial Python Binding of the tikv/raft-rs"
readme = "README.md"
license = { file = "LICENSE" }
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
]
