[package]
name = "utils"
version = "0.1.0"
authors = ["jopemachine"]
edition = "2018"

[dependencies]
pyo3 = { version = "0.18.3", features = ["extension-module", "multiple-pymethods"] }
bincode = "1.3.3"

[lib]
name = "utils"
path = "lib.rs"