name: Test Automation

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-rraft-py:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Set up pip and requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install protobuf compiler
      run: |
        sudo apt install -y protobuf-compiler
    - name: Set up Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        components: rustfmt, clippy
    - name: Set up Cargo
      uses: actions-rs/cargo@v1
    - name: Use rust nightly
      run: |
        rustup toolchain install nightly
        rustup override set nightly
    - name: Build and Test
      run: |
        make lint
        make install
        make test
